version = 0.1

[default]
[default.global]
[default.global.parameters]
s3_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-srhclqjttd3t"
region = "eu-central-1"
s3_prefix = "dev"

[default.package.parameters]
output_template_file = "packaged-dev.yaml"

[default.deploy.parameters]
template_file = "packaged-dev.yaml"
capabilities = "CAPABILITY_NAMED_IAM"

[dev]
[dev.deploy]
[dev.deploy.parameters]
parameter_overrides = "EnvName=dev"


[prod]
[prod.package]
[prod.package.parameters]
s3_prefix = "prod"
output_template-file = "packaged-prod.yaml"

[prod.deploy]
[prod.deploy.parameters]
stack_name = "s3-sns-prod"
template_file = "packaged-prod.yaml"
s3_prefix = "prod"
parameter_overrides = "EnvName=prod"